### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [ZhifangYe/neuro_docker#1]
hey @ZhifangYe ! I'm really glad to see that you are taking advantage of Singularity Hub! :) Would you mind deleting builds that you no longer need? It looks like you just hit 25 (all successful) and since we are storing (and paying for) each build, it's good container hygiene to keep this sort of thing in mind. If needed, you can also disable building for times when you anticipate high levels of commits, or just use a different branch for releases / Singularity Hub. Thank you!

**Comment by ZhifangYe** [comment]
Hi @vsoch , thanks for noticing. It seems that singularity-hub build the same images multiply times when I push other things to this repo. I didn't realize that the auto build detect all commits of this repo. I'm removing unnecessary images now. Sorry for the trouble! Also I think maybe a better strategy of auto build is to check Singularity file changes instead of commit?

I really love Singularity and Singularity-Hub. Thanks for building these amazing tools!

**Comment by vsoch** [comment]
haha thanks!! Yes, I'm actually working on an updated version of the hub, and I'm going to be changing the build flow a bit so it's easier to automatically have this taken care of. In the meantime, thank you for removing the unnecessary images! I'll keep working on this, and please don't hesitate to bother me if you have ideas or feedback for features that would be useful for you and your group. Closing issue!
